version: '3'

services:
  rs2server:
    container_name: rs2server
    hostname: rs2server
    image: rs2server:latest
    ports:
      - 7777:7777/udp
      - 27015:27015/udp
      - 8080:8080
    volumes:
      - /path/to/RS2:/RS2
